config/routes.rb
Rails.application.routes.draw do

  root 'providers#index'

  resources :users
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'show', to: 'movies#show'

  get 'likes', to: 'movies#likes'

  get 'like_movies', to: 'movies#like_movies'

  get 'netflix', to: 'movies#netflix'
  get 'hulu', to: 'movies#hulu'

  resources :comments, only: %i[create]

  resources :movies do
    resource :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  validates :user_id, uniqueness: { scope: :movie_id }
end

app/models/movie.rb
class Movie
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :id, :integer
  attribute :name, :string
  attribute :overview, :string
  attribute :poster_path, :string
  attribute :backdrop_path, :string
  attribute :first_air_date, :string
  attribute :genre_ids, :integer
  attribute :origin_country, :string
  attribute :original_language, :string
  attribute :original_name, :string
  attribute :popularity, :integer
  attribute :vote_average, :integer
  attribute :vote_count, :integer

  attribute :adult, :string                        
  attribute :backdrop_path, :string
  attribute :created_by, :string                    
  attribute :episode_run_time, :string            
  attribute :first_air_date, :string         
  attribute :genres, :string
  attribute :homepage, :string
  attribute :id, :integer                       
  attribute :in_production, :string            
  attribute :languages, :string                     
  attribute :last_air_date, :string      
  attribute :last_episode_to_air, :string
  attribute :name, :string
  attribute :next_episode_to_air, :string
  attribute :networks, :string
  attribute :number_of_episodes, :integer
  attribute :number_of_seasons, :integer
  attribute :origin_country, :string
  attribute :original_language, :string
  attribute :original_name, :string
  attribute :overview, :string
  attribute :popularity, :integer
  attribute :production_companies, :integer
  attribute :seasons, :string
  attribute :episode_count, :integer
  attribute :name, :string
  attribute :overview, :string
  attribute :poster_path, :string
  attribute :season_number, :string
  attribute :spoken_languages, :string
  attribute :status, :string
  attribute :tagline, :string
  attribute :type, :string
  attribute :vote_count, :integer
  attribute :production_countries, :string

  Netflix = "213"
  Hulu = "1772"
  Genre_Tension = "35"
  Genre_Chill = "10751|16"
  Genre_Exciting = "9648|10764|10759|10765"

  class << self
    def all(params)
      TmdbApi.all(params)
    end

    def like(params)
      TmdbApi.like(params)
    end

    def like_movies(params)
      TmdbApi.like_movies(params)
    end
  end
end

app/models/tmdb_api.rb
class TmdbApi
  class << self
    def all(params = {})
      provider_id = params[:provider_id]
      genre_id = params[:genre_id]
      provider = URI.encode_www_form({with_networks: provider_id})
      genre = URI.encode_www_form({with_genres: genre_id})
      tmdb = URI.parse("https://api.themoviedb.org/3/discover/tv?api_key=#{ENV['API_KEY']}&language=ja-JP&#{provider}&#{genre}")
      response = Net::HTTP.get(tmdb)
      tmdb_list = JSON.parse(response)
      uri = URI.parse("https://api.themoviedb.org/3/discover/tv?api_key=#{ENV['API_KEY']}&language=ja-JP&#{provider}&#{genre}&page=#{rand(tmdb_list['total_pages'])+1}")
      json = Net::HTTP.get(uri)
      data_list = JSON.parse(json)
      movie = data_list["results"]
      movie.map do |data|
        Movie.new(data)
      end
    end

    def like(params = {})
      user_id = params[:user_id]
      likes = Like.where(user_id: user_id).order(created_at: :desc).pluck(:movie_id)
      @likeslist = []
      likes.map do |id|
      uri = URI.parse("https://api.themoviedb.org/3/tv/#{id}?api_key=#{ENV['API_KEY']}&language=ja-JP")
      json = Net::HTTP.get(uri)
      result = JSON.parse(json)
      likeslist = result
      @likeslist += [likeslist]
      end
      list = @likeslist
      list.map do |list|
        Movie.new(list)
      end
    end

    def like_movies(params = {})
      movie_id = params[:movie_id].to_i
      uri = URI.parse("https://api.themoviedb.org/3/tv/#{movie_id}?api_key=#{ENV['API_KEY']}&language=ja-JP")
      json = Net::HTTP.get(uri)
      result = JSON.parse(json)
      movie = [result]
      movie.map do |data|
        Movie.new(data)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  add_flash_types :success, :info, :warning, :danger

  private

  def not_authenticated
    redirect_to login_path, danger: "ログインしてください"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      comment = current_user.comments.build(comment_params)
      if comment.save
        redirect_back(fallback_location: root_path) 
      else
        redirect_back(fallback_location: root_path) 
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:body).merge(movie_id: params[:movie_id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @movie_id = params[:movie_id]
    @like = current_user.likes.create(movie_id: @movie_id)
  end
    
  def destroy
    @movie_id = params[:movie_id]
    @like = current_user.likes.find_by(movie_id: @movie_id)
    @like.destroy
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    if @movies = Movie.all(params).sample
      flash.now[:success] = t('.success')
    else
      flash.now[:danger] = t('.fail')
      redirect_back(fallback_location: root_path)
    end
    @movie_id = @movies.id
    @comments = Comment.where(movie_id: @movie_id).includes(:user).order(created_at: :desc)
  end

  def likes
    @likes = Movie.like(params)
  end

  def like_movies
    @movie_id = params[:movie_id]
    @like_movies = Movie.like_movies(params).first
    @comment = Comment.new
    @comments = Comment.where(movie_id: @movie_id).includes(:user).order(created_at: :desc)
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <div class="card bg-dark text-white bg-opacity-75 mb-1">
    <div class="card-body">
       <p class="font-weight-hold"><%= comment.user.name %></p>
       <p class="card-text"><small><%= simple_format comment.body %></small></p>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-outline-light btn-lg w-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
        コメントする
      </button>
    </div>
    <div class="col-12 sidebar comments">
      <% if @comments.present? %>
        <%= render 'comments/comments', comments: @comments %>
      <% else %>
        <p>現在コメントはありません</p>
      <% end %>
    </div>
  </div>
</div> 

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-black" id="exampleModalLabel">感想を書いてみよう！</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with model: @comment, remote: true do |f| %>
        <div class="modal-body">
            <div class="form-group">
            <%= f.label :body, "コメント" %>
            <%= f.text_area :body, class:"form-control" %>
            <%= hidden_field_tag :movie_id, @movie_id %>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
            <%= f.submit "投稿する", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.comments').html("<%= escape_javascript(render 'comments/comments', comments: @comments) %>")

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-EWWDEMJ8V5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EWWDEMJ8V5');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscRoulette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>

  <body class="bg-dark text-white bg-opacity-75">
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if Like.exists?(user_id: current_user.id, movie_id: @movie_id) %>
  <%= link_to movie_likes_path(movie_id: @movie_id), class: "text-white", method: :delete, remote: true do %>
    <i class="fas fa-check fa-5x"></i>
    <span class="fa-pull-left">気になる</span>
  <% end %>
<% else %>
  <%= link_to movie_likes_path(movie_id: @movie_id),  class: "text-white", method: :post, remote: true do %>
    <i class="fas fa-plus fa-5x"></i>
    <span class="fa-pull-left">気になる</span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('.like').html('<%= j(render 'like', locals: { movie_id: @like.movie_id }) %>');

app/views/likes/destroy.js.erb
$('.like').html('<%= j(render 'like', locals: { movie_id: @like.movie_id }) %>');

app/views/movies/bookmark_show.html.erb
<div class="container">
  <div class="row">
    <div class="card mb-3 mt-5 bg-dark text-white bg-opacity-75">
      <div class="row g-0">
        <div class="col-md-6">
          <%= image_tag "https://image.tmdb.org/t/p/w1280/#{@like["poster_path"]}", class: "card-img" %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h5 class="card-title text-center"><%= @like["name"] %></h5>
            <p class="card-text text-center"><%= @like["overview"] %></p>
            <p class="card-text text-center"><small class="text-muted"><%= @like["id"] %></small></p>
            <div class="d-flex align-items-center justify-content-center">
              <div class="like" style="width: 70px;">
                <%= render partial: 'likes/like', locals: { user_id: current_user.id, movie_id: @movie_id } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>    
  </div>
</div>

app/views/movies/hulu.html.erb
<div class="container">
  <div class="row mt-5 p-5">
    <div class="col-md-4">
      <%= link_to "テンション上げたい", show_path(provider_id: Movie::Hulu, genre_id: Movie::Genre_Tension), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
    <div class="col-md-4">
      <%= link_to "チルしたい", show_path(provider_id: Movie::Hulu, genre_id: Movie::Genre_Chill), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
    <div class="col-md-4">
      <%= link_to "ハラハラしたい", show_path(provider_id: Movie::Hulu, genre_id: Movie::Genre_Exciting), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
  </div>
</div>

app/views/movies/like_movies.html.erb
<div class="container">
  <div class="row">
    <div class="card mb-3 mt-5 bg-dark text-white bg-opacity-75">
      <div class="row g-0">
        <div class="col-md-6">
          <%= image_tag "https://image.tmdb.org/t/p/w1280/#{@like_movies.poster_path}", class: "card-img" %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h5 class="card-title text-center"><%= @like_movies.name %></h5>
            <p class="card-text text-center"><%= @like_movies.overview %></p>
            <p class="card-text text-center"><small class="text-muted"><%= @like_movies.id %></small></p>
            <%= link_to "観に行く", @like_movies.homepage, class: "btn btn-outline-light btn-lg w-100" %>
            <div class="d-flex align-items-center justify-content-center">
              <div class="like" style="width: 70px;">
                <%= render partial: 'likes/like', locals: { user_id: current_user.id, movie_id: @movie_id } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 sidebar comments">
      <h2 class="bg-secondary text-center">コメント一覧</h2>
    </div>  
    <%= render 'comments/form' %>
  </div>
</div>

app/views/movies/likes.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4"">
    <% if @likes.present? %>
        <% @likes.each do |result| %>
        <div class="col">
            <div class="card bg-dark text-white bg-opacity-75">
            <%= image_tag "https://image.tmdb.org/t/p/w1280/#{result.poster_path}", class: "card-img" %>
            <div class="card-body">
                <p class="card-text"><%= result.name%></p>
                <%= link_to "詳細", like_movies_path(movie_id: result.id), class: "btn btn-outline-light btn-lg w-100" %>
            </div>
            </div>
        </div>
        <% end %>
    <% end %>
</div>

app/views/movies/netflix.html.erb
<div class="container">
  <div class="row mt-5 p-5">
    <div class="col-md-4">
      <%= link_to "テンション上げたい", show_path(provider_id: Movie::Netflix, genre_id: Movie::Genre_Tension), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
    <div class="col-md-4">
      <%= link_to "チルしたい", show_path(provider_id: Movie::Netflix, genre_id: Movie::Genre_Chill), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
    <div class="col-md-4">
      <%= link_to "ハラハラしたい", show_path(provider_id: Movie::Netflix, genre_id: Movie::Genre_Exciting), class: "btn btn-outline-light btn-lg w-100 mt-5" %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="row">
    <div class="card mb-3 mt-5 bg-dark text-white bg-opacity-75">
      <div class="row g-0">
        <div class="col-md-6">
          <%= image_tag "https://image.tmdb.org/t/p/w1280/#{@movies.poster_path}", class: "card-img" %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h5 class="card-title text-center"><%= @movies.name %></h5>
            <p class="card-text text-center"><%= @movies.overview %></p>
            <p class="card-text text-center"><small class="text-muted"><%= @movies.id %></small></p>
            <div class="d-flex align-items-center justify-content-center">
              <div class="like" style="width: 70px;">
                <% if logged_in? %>
                  <%= render partial: 'likes/like', locals: { user_id: current_user.id, movie_id: @movie_id } %>
                <% end %> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
    <div class="col-12 sidebar comments">
      <h2 class="bg-secondary text-center">コメント一覧</h2>
    </div>  
    <div class="col-12 sidebar comments">
      <% if @comments.present? %>
        <%= render 'comments/comments', comments: @comments %>
      <% else %>
        <p>現在コメントはありません</p>
      <% end %>
    </div>  
  </div>
</div>

app/views/providers/index.html.erb
<div class="container">
  <div class="row mt-5 p-5">  
    <div class="col-md-6">
      <%= link_to "Netflix", netflix_path, class: "btn btn-outline-danger btn-lg w-100 mt-5" %>
    </div>
    <div class="col-md-6">
      <%= link_to "Hulu", hulu_path, class: "btn btn-outline-success btn-lg w-100 mt-5" %>
    </div>
  </div>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="card bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">次観るドラマ・アニメを探そう！</h2>
          </div>        
        </div>
        <img src="/assets/top1.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">今回このサービスを作ったのは、私自身、仕事終わりや休日にサブスクを利用してドラマやアニメをよく観るのですが、「次何観るか」の選択肢が多数ぎて、選ぶのが面倒だなと思うことが多々あります。また、私がドラマやアニメを選ぶ基準は基本的に、ポスター画像が「いい感じ」かどうかです。そのため、ランダムでドラマ、アニメが表示され、かつ、ポスター画像やタイトル、概要で「いい感じ」のものが出て来れば、数多くの選択肢から選ぶよりも、運任せで気楽にサブスクを利用出来ると思い作成しました。</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">配信サービスを選ぼう！</h2>
          </div>        
        </div>
        <img src="/assets/top2.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">NetflixかHuluかを選択しよう！</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card  bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">シチュエーションを選ぼう！</h2>
          </div>        
        </div>
        <img src="/assets/top3.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">シチュエーションを選択しよう！シチュエーションを選択したら、ランダムでそのシチュエーションに合ったドラマ・アニメが出てくる！</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card  bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">「気になる」をしよう！</h2>
          </div>        
        </div>
        <img src="/assets/top4.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">ユーザー登録者は、気になる機能を使ってランダムで出てきたドラマを「気になるリスト」に保存することが出来る！※ゲストユーザーは気になるボタンは表示されません。</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card  bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">自分だけの気になるリスト！</h2>
          </div>        
        </div>
        <img src="/assets/top5.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">気になるリストは、次に観る候補として大活躍します！</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card  bg-dark text-white bg-opacity-75">
        <div class="card-body">
          <div class="col-12 sidebar comments ">
            <h2 class="bg-secondary text-center">感想を書こう！</h2>
          </div>        
        </div>
        <img src="/assets/top6.png" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">気になるリストから、ドラマ・アニメを見た後は感想を書いて、他のユーザーに共有しよう！</p>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<nav class="sticky-top shadow navbar navbar-light bg-dark">

    <%= link_to root_path, class:"navbar-brand ms-2" do %>
      <i class="fas fa-random text-white fs-2"></i>
      <span class="text-white fs-2">サブスクルーレット</span>
    <% end %>
    
    <% if logged_in? %>
      <%= link_to user_path(current_user), class: 'navbar-brand d-flex align-items-center me-3 text-light' do %>
        <i class="fas fa-user-circle fs-2 me-1"></i>
        <span><%= current_user.name %></span>
      <% end %> 
    <% else %>
      <%= link_to login_path, class: 'd-flex me-3 text-light' do %>
        <span>ログイン</span>
      <% end %>
    <% end %>  
</nav>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email, User.human_attribute_name(:email) %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, User.human_attribute_name(:password) %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'ログイン', class: 'btn btn-secondary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '新規登録ページへ', new_user_path, class: "text-white" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', @user, class: "text-white" %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', root_path, class: "text-white" %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="mt-5 fs-1 text-center">
       <i class="fas fa-user-circle fa-6x"></i>
      </div>
      <div class="fs-1 text-center">
       <%= @user.name %>
      </div>
       <div class="d-flex justify-content-around my-5">
       <div class="d-flex flex-column" style="width: 100px;">
        <%= link_to logout_path, method: :delete, class: 'text-white' do %>
         <i class="fas fa-sign-out-alt fa-5x"></i>
         <span class="fa-pull-left">ログアウト</span>
        <% end %>
       </div>
       <div class="d-flex flex-column" style="width: 150px;">
        <%= link_to edit_user_path(@user), class: 'text-white' do %>
          <i class="fas fa-pen fa-5x"></i>
          <span class="fa-pull-left">プロフィール編集</span>
        <% end %> 
       </div>
       <div class="d-flex flex-column" style="width: 120px;">
        <%= link_to likes_path(user_id: current_user.id), class: "text-white" do %>
         <i class="fas fa-plus fa-5x"></i>
         <span class="fa-pull-left">気になるリスト</span>
        <% end %>
       </div>
       </div>
    </div>
  </div>
</div>